In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

In [2]:
######################################################################################
# Number of training data
N_u = 1                        # Boundary condition data on u(x)  
N_r = 5000                     # Number of collocation points for minimizing the PDE residual
lb  = np.array([0.0])         # Left boundary of the domain
ub  = np.array([60000.0])          # Right boundary of the domain

# Generate training data
x_u = np.array([[0]])  ##TZ
y_u = np.array([[1,0,0]])   ##TZ                    # Solution at boundary points (dimension N_u x 1)
x_r = np.linspace(lb, ub, N_r)     # Location of collocation points (dimension N_r x 1)

In [3]:
def init_model(number_hidden_layers = 2, num_neurons_per_layer = 50):
    model = tf.keras.Sequential()
    model.add(tf.keras.Input(1))
    
    model.add(tf.keras.layers.Dense(num_neurons_per_layer, activation=tf.keras.activations.get('tanh'), 
                                    kernel_initializer='glorot_normal'))
    model.add(tf.keras.layers.Dense(num_neurons_per_layer, activation=tf.keras.activations.get('tanh'), 
                                    kernel_initializer='glorot_normal'))
    
    model.add(tf.keras.layers.Dense(3, activation=tf.keras.activations.get('softmax')))
    
    return model

In [4]:
model = init_model()

In [5]:
Xr_tf = tf.convert_to_tensor(x_r, dtype=tf.float32)
Xu_tf = tf.convert_to_tensor(x_u, dtype=tf.float32)

In [10]:
with tf.GradientTape(persistent=True) as g:
    g.watch(Xr_tf)

    u = model(Xr_tf)

    u1 = u[:,0:1]
    u2 = u[:,1:2]
    u3 = u[:,2:3]

#derivatives of state probability
u_x_1 = g.gradient(u1, Xr_tf)
u_x_2 = g.gradient(u2, Xr_tf)
u_x_3 = g.gradient(u3, Xr_tf)

In [11]:
u2

<tf.Tensor: shape=(5000, 1), dtype=float32, numpy=
array([[0.33333334],
       [0.22911815],
       [0.26446056],
       ...,
       [0.27418694],
       [0.27418694],
       [0.27418694]], dtype=float32)>

In [12]:
u_x_1

<tf.Tensor: shape=(5000, 1), dtype=float32, numpy=
array([[ 0.12887038],
       [-0.00588698],
       [-0.00103088],
       ...,
       [ 0.        ],
       [ 0.        ],
       [ 0.        ]], dtype=float32)>

In [13]:
g.gradient(u1, Xr_tf)

<tf.Tensor: shape=(5000, 1), dtype=float32, numpy=
array([[ 0.12887038],
       [-0.00588698],
       [-0.00103088],
       ...,
       [ 0.        ],
       [ 0.        ],
       [ 0.        ]], dtype=float32)>

In [1]:
import tensorflow.compat.v1 as tf
import numpy as np

tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
######################################################################################
# Number of training data
N_u = 1                        # Boundary condition data on u(x)  
N_r = 5000                     # Number of collocation points for minimizing the PDE residual
lb  = np.array([0.0])         # Left boundary of the domain
ub  = np.array([60000.0])          # Right boundary of the domain

# Generate training data
x_u = np.array([[0]])  ##TZ
y_u = np.array([[1,0,0]])   ##TZ                    # Solution at boundary points (dimension N_u x 1)
x_r = np.linspace(lb, ub, N_r)     # Location of collocation points (dimension N_r x 1)

In [7]:
Xr_tf = tf.convert_to_tensor(x_r, dtype=tf.float32)
Xu_tf = tf.convert_to_tensor(x_u, dtype=tf.float32)

In [8]:
def init_model(number_hidden_layers = 2, num_neurons_per_layer = 50):
    model = tf.keras.Sequential()
    model.add(tf.keras.Input(1))
    
    model.add(tf.keras.layers.Dense(num_neurons_per_layer, activation=tf.keras.activations.get('tanh'), 
                                    kernel_initializer='glorot_normal'))
    model.add(tf.keras.layers.Dense(num_neurons_per_layer, activation=tf.keras.activations.get('tanh'), 
                                    kernel_initializer='glorot_normal'))
    
    model.add(tf.keras.layers.Dense(3, activation=tf.keras.activations.get('softmax')))
    
    return model

In [9]:
model = init_model()

In [21]:
u = model(Xr_tf)
u1 = u[:,0:1]
u2 = u[:,1:2]
u3 = u[:,2:3]

#derivatives of state probability
u_x_1 = tf.gradients(u1, Xr_tf)[0]
u_x_2 = tf.gradients(u2, Xr_tf)[0]
u_x_3 = tf.gradients(u3, Xr_tf)[0]

In [27]:
u1

<tf.Tensor 'strided_slice_12:0' shape=(5000, 1) dtype=float32>

In [23]:
u2

<tf.Tensor 'strided_slice_13:0' shape=(5000, 1) dtype=float32>

In [24]:
u3

<tf.Tensor 'strided_slice_14:0' shape=(5000, 1) dtype=float32>

In [30]:
u_x_1

<tf.Tensor 'gradients_7/sequential_1_3/dense_3/MatMul_grad/MatMul:0' shape=(5000, 1) dtype=float32>

In [31]:
u_x_2

<tf.Tensor 'gradients_8/sequential_1_3/dense_3/MatMul_grad/MatMul:0' shape=(5000, 1) dtype=float32>